### ISSUE TITLE
Create a form for the user to upload files with required fields

### ISSUE THREAD

**Issue by JumperGerald** [FNLHub/virtualMuseum#3]
To view a 3d object the following files are required:

object.obj
material.mtl
material.jpg
thumbnail.png
________

To accomplish this, duplicate and modify the "Choose File" Button for each of the required fields. When a file is selected be sure to validate that the extension matches the extensions listed above.

**Comment by JumperGerald** [comment]
The form will also need some text fields for title, description, author, etc.

**Comment by BusherBridi** [comment]
I added an accept tag to the buttons to limit the extension types the user can upload, however this is done client side and therefore not secure.
